### ISSUE TITLE
Redesign: Astronomy

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1794]
**Primary focus**: Available light

**Secondary focus**: Cool astronomical events (meteor showers, eclipses)

**At a glance**:
- Time until sunrise/sunset
- Sunrise / sunset
- Length of day
- Moonrise / moonset
- Moon phase
- Meteor shower peak
- Meteor shower rate
- Eclipse start/end
- Eclipse obscuration

**Advanced**:
- Civil/Nautical/Astronomical times
- Noon time
- Season
- Super moon
- Rise / set direction
- Peak altitude / direction
- Length of night
- Meteor shower name
- Eclipse duration
- Eclipse magnitude

**Mockup**:
![before-and-after](https://github.com/kylecorry31/Trail-Sense/assets/5938560/383cb861-a1c8-4a02-8ac5-0fcdaf6b427c)

**Task list**:
- [x] Create at a glance view
- [x] Update "until" text to always say sunrise/sunset
- [x] Create advanced dialogs (list view, similar style as main astronomy)
- [x] Remove old field code
- [x] Remove unused strings
- [x] Remove unused preferences
- [x] Replace the astronomy icon with a crescent moon (with a star?)
- [x] Re-evaluate the astronomy altitude chart - is that easy to understand? is there a better format that supports at a glance viewing (moving that to the advanced dialogs)? what value does it provide?
- [x] Add the search button
