### ISSUE TITLE
Redesign: Weather

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1795]
Weather doesn't need much work, since the last update tried to re-focus it.

**Primary focus**: Weather prediction

**At a glance**:
- Weather prediction (now, later)
- Temperature prediction (high / low)
- Current observations (pressure, tendency - maybe just direction, temperature)
- Alerts (storm, cold, hot)

**Advanced**:
- Pressure history (may remain in at a glance until #1509 )
- Pressure tendency (exact amount)
- Pressure system
- Weather front
- Temperature history
- Temperature prediction (not in at a glance because it is estimated on historic values, so a rough estimate)

**Task list**:
- [ ] Create at a glance view
- [ ] Create advanced dialogs
- [ ] Remove old field code
- [ ] Re-evaluate the pressure chart - is this easy to understand for most people, or is pressure a more technical indicator? Maybe this gets replaced after #1509 and moved into the advanced pressure dialog

**Comment by kylecorry31** [comment]
UI design idea (will draw out a mockup later)

Title: Current weather, later weather (stays the same)
Chart: Pressure history (will be replaced once #1509 is completed)
Data:
- Alerts: Storm, Cold, Hot
- Temperature: Low, Current, High
  - On click: Show next 24 hours prediction with last X hours recorded 
- Pressure: Current, Tendency
  - On click: Show last X hours recorded, pressure system, weather front 
- Humidity: Humidity
  - On click: Show last X hours recorded

**Comment by kylecorry31** [comment]
This will also be needed for #3176

**Comment by kylecorry31** [comment]
I'll make any required changes when I add the weather plugin. No other changes needed right now
