### ISSUE TITLE
Augmented reality tool [Tracking Issue]

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#2024]
- [x] Expose via experimental settings
- [x] #1702 
- [x] #608 
- [x] #1802 
- [x] #2104  (Prior to release)
- [x] Support linking from other tools with context (using temporary layer setting overrides)
- [x] #2138 
- [x] Show current azimuth and elevation (at the top of the screen)
- [x] Show a compass on the horizon
- [x] #2023 
- [x] #2232 (Prior to beta)
- [x] #2025 
- [x] #2103
- [x] #2194 (Prior to beta)
- [x] #2113 (Prior to beta)
- [x] #2042 (Prior to beta)
- [x] #2243 (Prior to release)
- [x] #2252
- [x] Full release

**Comment by michaelblyons** [comment]
This seems extremely cool. Are there device limitations or external apps (ARCore?) required for the AR stuff to work?

**Comment by kylecorry31** [comment]
@michaelblyons there shouldn't be any limitations for this to work - other than your phone needs a compass/accelerometer for it to match the rotation of the device (though there will be a version that you can manually drag) and a back facing camera if you want the full AR experience. A gyroscope would be helpful too, but it can work without that (just won't be as accurate / responsive).

I'm building it from scratch, so it doesn't depend on any external apps.

The only thing I'm not sure about is if all devices report camera field of view - the docs imply that it does, but I'm not sure I trust that because I've seen other things that some manufacturers just ignore. I may add a manual calibration option if I find this to be the case (or maybe add it just in case)

This tool is available on the Nightly builds if you wanted to try it out: https://github.com/kylecorry31/Trail-Sense/discussions/1940

Turn on Settings > Experimental > Augmented Reality, then open the Tools > Augmented Reality. It's super early (as in I built it within the last couple days), so I'm sure there are bugs / unoptimized or approximate algorithms. Currently it will display the sun / moon positions and nearby beacons. I also noticed it is off by about a degree on my device, which may be the maximum accuracy I can get on a phone without some fancy computer vision algorithms (I was thinking of auto-calibrating using the actual sun/moon), but haven't researched that much.

I would love to get feedback on this tool and hear ideas for what I can include in it (feel free to post ideas here). You can see some planned features by using the label:augmented-reality in the issue search.
