### ISSUE TITLE
Tools: Hydration Tracker

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#2412]
- [ ] Calculate water needed for path (factor in temperature, path difficulty, pack weight, user weight/other relevant factors)
- [ ] Reminder to drink water (configurable at specified interval)
- [ ] Reminder to replenish water (timer and/or #1908)
- [ ] Water weight calculator (show when water needed is calculated)
